export * from "./categories";
export * from "./registry";
export * from "./types";

import { registerAdminTools } from "./tools/admin";
import { registerApplicationTools } from "./tools/application";
import { registerBackupTools } from "./tools/backup";
import { registerBitbucketTools } from "./tools/bitbucket";
import { registerCertificateTools } from "./tools/certificate";
import { registerClusterTools } from "./tools/cluster";
import { registerComposeTools } from "./tools/compose";
import { registerDeploymentTools } from "./tools/deployment";
import { registerDestinationTools } from "./tools/destination";
import { registerDockerTools } from "./tools/docker";
import { registerDomainTools } from "./tools/domain";
import { registerEnvVarTools } from "./tools/env-vars";
import { registerEnvironmentTools } from "./tools/environment";
import { registerGitProviderTools } from "./tools/git-provider";
import { registerGiteaTools } from "./tools/gitea";
import { registerGithubTools } from "./tools/github";
import { registerGitlabTools } from "./tools/gitlab";
import { registerMariadbTools } from "./tools/mariadb";
import { registerMongoTools } from "./tools/mongo";
import { registerMountTools } from "./tools/mount";
import { registerMysqlTools } from "./tools/mysql";
import { registerNotificationTools } from "./tools/notification";
import { registerOrganizationTools } from "./tools/organization";
import { registerPortTools } from "./tools/port";
import { registerPostgresTools } from "./tools/postgres";
import { registerPreviewDeploymentTools } from "./tools/preview-deployment";
import { registerProjectTools } from "./tools/project";
import { registerRedirectTools } from "./tools/redirects";
import { registerRedisTools } from "./tools/redis";
import { registerRegistryTools } from "./tools/registry";
import { registerRollbackTools } from "./tools/rollbacks";
import { registerScheduleTools } from "./tools/schedule";
import { registerSecurityTools } from "./tools/security";
import { registerServerTools } from "./tools/server";
import { registerSettingsTools } from "./tools/settings";
import { registerSshKeyTools } from "./tools/ssh-key";
import { registerStripeTools } from "./tools/stripe";
import { registerSwarmTools } from "./tools/swarm";
import { registerTraefikTools } from "./tools/traefik";
import { registerUserTools } from "./tools/user";
import { registerVolumeBackupTools } from "./tools/volume-backups";

let toolsInitialized = false;

export function initializeTools() {
	if (toolsInitialized) return;

	registerAdminTools();
	registerDockerTools();
	registerProjectTools();
	registerEnvironmentTools();
	registerPostgresTools();
	registerMysqlTools();
	registerMariadbTools();
	registerMongoTools();
	registerRedisTools();
	registerApplicationTools();
	registerServerTools();
	registerOrganizationTools();
	registerMountTools();
	registerEnvVarTools();
	registerPortTools();
	registerComposeTools();
	registerDeploymentTools();
	registerPreviewDeploymentTools();
	registerDestinationTools();
	registerNotificationTools();
	registerGitProviderTools();
	registerGiteaTools();
	registerBitbucketTools();
	registerGitlabTools();
	registerGithubTools();
	registerDomainTools();
	registerRedirectTools();
	registerRegistryTools();
	registerScheduleTools();
	registerBackupTools();
	registerVolumeBackupTools();
	registerCertificateTools();
	registerClusterTools();
	registerSwarmTools();
	registerSshKeyTools();
	registerRollbackTools();
	registerSecurityTools();
	registerTraefikTools();
	registerSettingsTools();
	registerUserTools();
	registerStripeTools();

	toolsInitialized = true;
}
